### PR TITLE
Fix compatibility with Propshaft 1.3.0

### PR DESCRIPTION
**Pull request by beetlegius-somos**
## Description

This PR fixes the issue reported in #118 where roadie-rails doesn't work correctly with Propshaft 1.3.0.

## Problem

The `config.after_initialize` block was not executing correctly with Propshaft 1.3.0, causing the `AssetPropshaftProvider` not to be initialized. This resulted in the error:

```
NoMethodError: undefined method '[]' for an instance of Propshaft::Assembly
```

## Solution

- Modified `railtie.rb` to properly detect `Propshaft::Assembly` instances
- Initialize `AssetPropshaftProvider` immediately instead of using the `after_initialize` block
- Added type checking to distinguish between Sprockets and Propshaft

## Changes

- `lib/roadie/rails/railtie.rb`: Improved Propshaft detection logic and provider initialization

## Testing

- ✅ Rails 8.0 tests with Propshaft pass correctly
- ✅ No linting errors introduced
- ✅ Solution is backward compatible

## References

- Issue #118: Propshaft 1.3.0 changes breaks it
- PR #119: Reference structure for documentation

Fixes #118

### CODE REVIEW

**Review by Mange — APPROVED** [review]
Looks really good! Thank you! ❤️

**Comment by Mange** [comment]
Version 3.4.0 was just pushed with this fix included. Thank you for your contribution! :heart:
